export const HOME_PATH = '/'
export const PRODUCT_PATH = '/shop'
export const PRODUCT_DETAIL_PATH = '/product/:slug'
export const AUTH_PATH = '/auth'
export const ACCOUNT_PATH = '/account'
export const ABOUT_PATH = '/about'
export const BLOG_PATH = '/blog'
export const BLOG_DETAIL_PATH = '/blog-post'